# @package _global_
defaults:
  - /env: smoke_env
  - /agent: dubins

data_collection:
  num_samples: 10000
  output_dir: "data/raw"
  output_filename: "global_collected_source_400_100_2nd_10000.npz"
  playback_path: "/Users/emanuelsamir/Documents/dev/cmu/research/experiments/7_safe_nav_smoke/data/playback_data/global_source_400_100_2nd.npz"
  num_robots: 20 # Virtual fleet to speed up collection
  num_smoke_blobs: 8
  
  sensor:
    type: "downwards"
    points_in_range: 32
    fov_size_degrees: 50

  smoke:
    resolution: 0.4
    intensity: 1.0
    spread_rate: 1.0

env:
  max_steps: 100 # Override default
